Migrate to GitHub Actions
infrawatch/sg-core pull request #18
Opened 2020-11-26 22:22 UTC by leifmadsen

2020-11-26 23:45 UTC, leifmadsen commented
This should merge before #19

2020-11-27 09:16 UTC, mrunge requested changes
Thank you for working on this. The only nit I have is the use of yum vs. dnf (in RHEL8+ preferred).

2020-11-27 16:38 UTC, mrunge approved these changes

2020-11-27 16:39 UTC, merged

2020-11-27 18:25 UTC, leifmadsen commented
![](https://github.trello.services/images/mini-trello-icon.png) [Migrate from Travis-CI to GitHub Actions](https://trello.com/c/QVFdw42L/1210-migrate-from-travis-ci-to-github-actions)